### ISSUE TITLE
Get OpenQuake to run in GitHub Actions with a sample dataset

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/opendrr-platform#121]
Reference: Slack DM with Joost on 2021-04-01, etc.

See initial OpenQuake installation in a GitHub Actions at https://github.com/anthonyfok/github-experiments

**Comment by anthonyfok** [comment]
Initial progress:

Got OpenQuake to run with a job.ini from CanadaSHM6 (yay!),
but the 6-hours-per-job limit on GitHub-hosted runners was reached before completion.
Full logs here:

* macOS: https://github.com/anthonyfok/github-experiments/runs/2522295569?check_suite_focus=true
* Ubuntu: https://github.com/anthonyfok/github-experiments/runs/2522218354?check_suite_focus=true

Need to find a smaller sample regional (instead of national) dataset and see if it can be processed within 6 hours.

**Comment by anthonyfok** [comment]
`oq engine --run` vs `oq run`?
See "20.3 Understanding the engine" on page 86 in https://docs.openquake.org/oq-engine/advanced/OpenQuakeforAdvancedUsers.pdf

**Comment by anthonyfok** [comment]
Follow up in:
* https://github.com/OpenDRR/OpenQuake-GitHub-Actions-demo (private repo storing data set)
* https://github.com/OpenDRR/OpenQuake-GitHub-Actions-demo-public (public repo actually running the GitHub Actions)

**Comment by jvanulde** [comment]
@anthonyfok can we close this?

**Comment by anthonyfok** [comment]
> @anthonyfok can we close this?

Good catch!  Thank you Joost!  Yes, let's close this.
