### ISSUE TITLE
User Story: Contact information for hazard experts

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/opendrr-platform#22]
As an Emergency Manager, Community Planner, Financial Risk Manager, I would like to have access to experts on hazards in an area of interest so that I can receive technical assistance.

_Source: https://github.com/OpenDRR/documentation/blob/master/docs/opendrr-platform.adoc#623-use-case-c-aggregation-area-analysis--reporting_

**Comment by jvanulde** [comment]
@NickyHastings, @malaikau what is the capacity demand required to deliver on this? Is this something we want to address in RiskProfiler?

**Comment by malaikau** [comment]
I too would like free access to experts of many kinds, but we are not going to do this. :) The idea is to provide enough info as stand-alone on the platform that we create less interaction with our experts, not more. Our capacity is too limited on this.
