### ISSUE TITLE
Conceptual framing of data model  (taxonomies) to guide onboarding of hazard and risk collections to PostGIS database

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/opendrr-platform#80]

**Comment by mjourneay** [comment]
v1.0 of data model taxonomies to guide onboarding of hazard and risk collections to PostGIS is complete. Backbone data model schema for physical-exposure, multi-hazard-threat and social-vulnerability will support transformation of national-level collections in OpenDRR/model-inputs. The scenario-risk-schema table supports transformation of sample data in OpenDRR/opendrr-data-store/sample-datasets/
